### ISSUE TITLE
I2C channels

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/COMMSBoard_PCB#2]
Should we also consider moving INA3221 to a different I2C channel from the sensors? I think it was causing us problems in the past having them in the same channels. You have an empty I2C channel on PD12 and PD13 pins which I think wont be a trouble routing. 

![image](https://github.com/PeakSat/COMMSBoard_PCB/assets/48751090/b68924b9-47d5-4da0-b36d-482cffbb75e4)

**Comment by giatats** [comment]
Added separate I2C Bus for INA (I2C4). Also added pull ups 5k.
