### ISSUE TITLE
Temperature Sensor

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/COMMSBoard_PCB#3]
In the previous version we had selected the TMP117MAIDRVR temperature sensors. From the datasheet these appear to have a lower temperature range than some other versions of the same component.

I think this mostly concerns the BOM but lets make sure that the other version donot have any differences in the footprint.

![image](https://github.com/PeakSat/COMMSBoard_PCB/assets/48751090/8411b3b1-a561-4244-b524-2bf2c8a54e57)

**Comment by giatats** [comment]
They are the same, we need to get either the TMP117AIDRVR or TMP117NAIDRVR.

**Comment by Basilhs-Moustakas** [comment]
Generated BOM taking this into account
