### ISSUE TITLE
GNSS power supply

### ISSUE THREAD

**Issue by Basilhs-Moustakas** [PeakSat/COMMSBoard_PCB#4]
I understand the logic for the GNSS power supply but maybe we could also add a 0 ohm resistor between 3V3_RF and V_BCKP and also a "Donot place" 0 Ohm resistor between VCC and V_BCKP just in case we decide in the future to switch to our old configuration, 

![image](https://github.com/PeakSat/COMMSBoard_PCB/assets/48751090/0a5a0012-99f2-45ac-8319-1c7cc0f81c04)

**Comment by giatats** [comment]
Schematic Updated
